In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [5]:
df = pd.read_csv('data/stud.csv')

In [3]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [6]:
df.shape

(1000, 8)

In [8]:
#check the missing values
df.isnull().sum()

gender                         0
race_ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

In [9]:
#no missing values in the dataset

In [10]:
#check for duplicate values
df.duplicated().sum()

np.int64(0)

In [11]:
# no duplicate values in the dataset

In [12]:
#checking the datatype
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race_ethnicity               1000 non-null   str
 2   parental_level_of_education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test_preparation_course      1000 non-null   str
 5   math_score                   1000 non-null   int64
 6   reading_score                1000 non-null   int64
 7   writing_score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

In [13]:
df.sample()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
505,female,group B,some high school,standard,none,82,82,80

In [14]:
#checking the unique values of each column
df.nunique()

gender                          2
race_ethnicity                  5
parental_level_of_education     6
lunch                           2
test_preparation_course         2
math_score                     81
reading_score                  72
writing_score                  77
dtype: int64

In [16]:
df.describe()

       math_score  reading_score  writing_score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [20]:
# unique values of each columns
for col in df.columns[:5]:
    print(f"Unique values in {col}: {df[col].unique()} \n")

Unique values in gender: <StringArray>
['female', 'male']
Length: 2, dtype: str

Unique values in race_ethnicity: <StringArray>
['group B', 'group C', 'group A', 'group D', 'group E']
Length: 5, dtype: str

Unique values in parental_level_of_education: <StringArray>
[ 'bachelor's degree',       'some college',    'master's degree',
 'associate's degree',        'high school',   'some high school']
Length: 6, dtype: str

Unique values in lunch: <StringArray>
['standard', 'free/reduced']
Length: 2, dtype: str

Unique values in test_preparation_course: <StringArray>
['none', 'completed']
Length: 2, dtype: str

In [21]:
# classifying numerical and catagorical features:
num_cols = df.select_dtypes(include=np.number).columns
cat_cols = df.select_dtypes(exclude=np.number).columns
print(num_cols, "\n", cat_cols)

Index(['math_score', 'reading_score', 'writing_score'], dtype='str')
 Index(['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course'],
      dtype='str')

Feature Engineering

In [24]:
#total_score and percentage
df['total_score'] = df['math_score'] + df['reading_score'] + df['writing_score']
df['percentage'] = np.round(df['total_score'] / 3,2)
df.head(1)

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,total_score,percentage
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.67

In [27]:
#number of students with the full marks.
print(f"Number of students with full marks in every subjects: {df[df['percentage'] == 100].shape[0]} \n")
print(f"Number of students with full marks in reading_score: {df[df['reading_score']==100].shape[0]} ")
print(f"Number of students with full marks in writing_score: {df[df['writing_score']==100].shape[0]} ")
print(f"Number of students with full marks in math_score: {df[df['math_score']==100].shape[0]} ")

Number of students with full marks in every subjects: 3

Number of students with full marks in reading_score: 17
Number of students with full marks in writing_score: 14
Number of students with full marks in math_score: 7